name: QA Automation - SauceDemo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  testes:
    name: Rodar testes Selenium
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Instalar ChromeDriver compatível
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Chrome version: $CHROME_VERSION"
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          chmod +x chromedriver-linux64/chromedriver
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          chromedriver --version

      - name: Executar testes
        run: behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results
        env:
          CHROMEDRIVER_PATH: /usr/local/bin/chromedriver

      - name: Salvar relatório Allure
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: reports/allure-results/

      - name: Salvar screenshots de falhas
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/
